version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t jamallasomasekhar/upload-pic .
      - echo Tagging the Docker image...
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push jamallasomasekhar/upload-pic:latest
artifacts:
  files: '**/*'
